matrix:
  include:
    - language: ruby
      rvm:
        - 2.4.1
      script:
        - bundle exec rspec spec/

    - language: node_js
      node_js: 
        - 8.2.1
      install:
        - npm install newman
        - gem install sinatra
        - gem install sinatra-contrib
        - gem install tic_tac_toe_rz
      before_script:
        - node --version
        - npm --version
        - node_modules/.bin/newman --version
        - cd /home/travis/.rvm/gems/ruby-2.4.1/gems/tic_tac_toe_rz-1.0.09/lib/tic_tac_toe_rz/TicTacToeRuby.Core/Languages/config/
        - ls
        - cd -
        - ruby tic_tac_toe_web.rb&
      script:
        - node_modules/.bin/newman run postman/tests.postman_collection.json

