source "https://rubygems.org"
ruby "2.5.0"
gem "rspec"
gem "tic_tac_toe_rz"
gem "sinatra"
gem "sinatra-contrib"
gem "capistrano", require: false
gem "capistrano-rbenv"
gem "capistrano-bundler"
gem "capistrano-rvm"
gem "backports"
gem "diff-lcs"
gem "multi_json"
gem "mustermann"
gem "rack-protection"